/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const IggrowbotApiCredentials = IDL.Record({
  'apiKey' : IDL.Text,
  'apiUrl' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'status' : OrderStatus,
  'cost' : IDL.Float64,
  'link' : IDL.Text,
  'user' : IDL.Principal,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Text,
  'apiOrderId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'utr' : IDL.Text,
  'status' : PaymentStatus,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const IggrowbotService = IDL.Record({
  'id' : IDL.Text,
  'max' : IDL.Nat,
  'min' : IDL.Nat,
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'creditUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCredentials' : IDL.Func([], [IggrowbotApiCredentials], ['query']),
  'getLowBalanceThreshold' : IDL.Func([], [IDL.Float64], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getOrderAmount' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(IggrowbotService)], ['query']),
  'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isLowBalance' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setLowBalanceThreshold' : IDL.Func([IDL.Float64], [], []),
  'submitPayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'syncServices' : IDL.Func([], [], []),
  'toggleLowBalanceAlert' : IDL.Func([], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyPayment' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const IggrowbotApiCredentials = IDL.Record({
    'apiKey' : IDL.Text,
    'apiUrl' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'status' : OrderStatus,
    'cost' : IDL.Float64,
    'link' : IDL.Text,
    'user' : IDL.Principal,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Text,
    'apiOrderId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'utr' : IDL.Text,
    'status' : PaymentStatus,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const IggrowbotService = IDL.Record({
    'id' : IDL.Text,
    'max' : IDL.Nat,
    'min' : IDL.Nat,
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'creditUser' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCredentials' : IDL.Func([], [IggrowbotApiCredentials], ['query']),
    'getLowBalanceThreshold' : IDL.Func([], [IDL.Float64], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getOrderAmount' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getPendingPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(IggrowbotService)], ['query']),
    'getUserBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isLowBalance' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setLowBalanceThreshold' : IDL.Func([IDL.Float64], [], []),
    'submitPayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'syncServices' : IDL.Func([], [], []),
    'toggleLowBalanceAlert' : IDL.Func([], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyPayment' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };